stages:
  - build

build:
  image: docker:24-git
  stage: build
  rules:
    - if: $PIPELINE == 'deploy'
      when: never
    - when: always
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --target production -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
